Fix LanguageCode error in opengraph.html
Error: can't evaluate field LanguageCode in type *langs.Language
Fix: Changed $site.Language.LanguageCode to $site.Language.Lang

This is a Hugo 0.124+ breaking change where LanguageCode was replaced with Lang.